In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np

In [3]:
import sys
sys.path.append('../..')

In [4]:
from dstableFGM import dstableFGM, projectPSD, graddstableform, dstable_descent

In [5]:
A = np.random.normal(size=(50, 50), scale=2/np.sqrt(50))

In [6]:
np.linalg.eigvals(A)

array([-1.93101908+0.41155097j, -1.93101908-0.41155097j,
       -0.93045933+1.71102271j, -0.93045933-1.71102271j,
       -0.53869332+1.83077936j, -0.53869332-1.83077936j,
       -1.59164755+0.92569726j, -1.59164755-0.92569726j,
       -1.70700008+0.11245852j, -1.70700008-0.11245852j,
       -1.16371574+1.14659373j, -1.16371574-1.14659373j,
        0.50659224+1.84111087j,  0.50659224-1.84111087j,
        1.03319474+1.60597189j,  1.03319474-1.60597189j,
        1.98662727+0.68018456j,  1.98662727-0.68018456j,
       -0.65601094+1.41310094j, -0.65601094-1.41310094j,
        2.00186549+0.j        , -1.05969781+0.63275401j,
       -1.05969781-0.63275401j, -0.19621335+1.3451534j ,
       -0.19621335-1.3451534j ,  0.14614914+1.37228847j,
        0.14614914-1.37228847j,  1.55227671+0.63307999j,
        1.55227671-0.63307999j,  1.68857872+0.j        ,
       -1.07439073+0.j        ,  1.19073453+0.71616756j,
        1.19073453-0.71616756j,  1.25702614+0.20759382j,
        1.25702614-0.20759382j,

In [115]:
np.abs(np.linalg.eigvals(A))

array([9.68793551e-01, 8.60206240e-01, 8.60206240e-01, 7.89895823e-01,
       7.89895823e-01, 8.77206180e-01, 8.77206180e-01, 8.95120717e-01,
       8.95120717e-01, 8.69371334e-01, 8.69371334e-01, 8.58927635e-01,
       8.58927635e-01, 8.77758634e-01, 8.77758634e-01, 8.45738603e-01,
       8.45738603e-01, 6.79354109e-01, 6.79354109e-01, 8.87781603e-01,
       8.87781603e-01, 9.08744620e-01, 9.08744620e-01, 8.37882089e-01,
       8.37882089e-01, 8.45661524e-01, 8.45661524e-01, 8.42784869e-01,
       8.42784869e-01, 8.85511959e-01, 8.85511959e-01, 8.83359453e-01,
       8.83359453e-01, 8.85167544e-01, 8.85167544e-01, 9.08758441e-01,
       9.08758441e-01, 8.71693106e-01, 7.13430824e-01, 7.13430824e-01,
       6.31947060e-01, 6.31947060e-01, 4.44751816e-01, 5.25029900e-01,
       5.25029900e-01, 4.23060059e-01, 4.23060059e-01, 2.56527203e-01,
       2.56527203e-01, 1.03776099e-15])

In [7]:
A = dstable_descent(A, maxiter=200, tol=1e-3, init='default')

/home/akumar/anaconda3/envs/dyn/lib/python3.7/site-packages/torch/functional.py:1403: UserWarning: torch.chain_matmul is deprecated and will be removed in a future PyTorch release. Use torch.linalg.multi_dot instead, which accepts a list of two or more tensors rather than multiple parameters. (Triggered internally at  /opt/conda/conda-bld/pytorch_1623448224956/work/aten/src/ATen/native/LinearAlgebra.cpp:697.)
  return _VF.chain_matmul(matrices)  # type: ignore[attr-defined]


81.80265155294788
32.88491176633413
32.81101569653935
32.230085867642195
30.76871274681497
28.37675038894923
25.9354818511033
25.764520840335283
24.906177556063067
22.90353613811283
22.81018840933624
22.501569069958784
21.725192877589745
21.072687785743344
20.819154681085
20.73715728166247
20.314070788076823
19.98550651125235
19.848185932839925
19.769962909548173
19.649620594394946
19.2919492861148
19.22264191118134
18.876706487010505
18.78867078353494
18.6755560580669
18.640176347628184
18.33666437320032
18.33112217856557
18.29815709485089
18.222072658941162
17.857872702571015
17.807280341392982
17.78375211110125
17.645786570339506
17.384453664728404
17.342704227714943
17.305502415654956
17.18365586399756
16.976901271857233
16.938999159700042
16.890333866366316
16.78593167611213
16.6198913569977
16.5790041384089
16.5203011806614
16.432648934396266
16.30407179776254
16.256924375183825
16.192708832421545
16.12017299327066
16.107330745565022
15.990383063516736
15.91645447959739
15.862706

### Peanut

In [23]:
from stability_correct import stability_correct_VAR
from loaders import load_peanut
from pyuoi.linear_model.var import VAR
from neurosim.models.var import VAR as VARss
from neurosim.models.var import form_companion

In [15]:
data_file = '/mnt/Secondary/data/peanut/data_dict_peanut_day14.obj'

In [33]:
# There is no need to do this across epochs, we just need to plot a stable matrix, so stick to the first epoch.
loader_args = {'bin_width':25, 'epoch': 4, 'filter_fn':'none', 'filter_kwargs':{}, 'boxcox':0.5, 'spike_threshold':100}
dat = load_peanut(data_file, **loader_args, region='HPc')

In [34]:
y = np.squeeze(dat['spike_rates'])

In [44]:
varmodel = VAR(estimator='ols', order=4)
varmodel.fit(y)

Rows of VAR matrix processed: 54it [00:01, 29.92it/s]


In [45]:
A = form_companion(varmodel.coef_)

In [46]:
np.abs(np.linalg.eigvals(A))

array([5.45875128e+03, 5.45852688e+03, 1.35578411e+00, 1.35578411e+00,
       1.00000000e+00, 8.90174367e-01, 8.90174367e-01, 8.57281022e-01,
       8.57281022e-01, 9.13428533e-01, 8.94555200e-01, 8.86949903e-01,
       8.45171421e-01, 8.45171421e-01, 8.37897349e-01, 7.86899138e-01,
       7.86899138e-01, 8.32712183e-01, 8.32712183e-01, 8.17420384e-01,
       8.17420384e-01, 7.89051702e-01, 7.89051702e-01, 7.63872183e-01,
       7.63872183e-01, 7.61667571e-01, 7.61667571e-01, 7.10339949e-01,
       7.10339949e-01, 7.06479824e-01, 7.06479824e-01, 7.01323759e-01,
       7.01323759e-01, 7.19561341e-01, 7.19561341e-01, 6.58138012e-01,
       6.20985111e-01, 6.20985111e-01, 7.28289084e-01, 7.13679162e-01,
       7.13679162e-01, 6.93433865e-01, 6.93433865e-01, 6.76839048e-01,
       6.76839048e-01, 5.82280282e-01, 5.82280282e-01, 6.76651520e-01,
       6.76651520e-01, 6.66368886e-01, 6.66368886e-01, 6.68766525e-01,
       6.68766525e-01, 6.65870439e-01, 6.65870439e-01, 6.54390360e-01,
      

In [48]:
# We can generate a stable A matrix no problem....choose smaller VAR orders