In [1]:
%load_ext autoreload
%autoreload 2

In [4]:
from pyuoi.linear_model.var import _form_cvar_problem, VAR
import numpy as np
from glob import glob
import sys

In [5]:
sys.path.append('/home/akumar/nse/neural_control')

In [6]:
from loaders import load_sabes

In [17]:
y = np.random.normal(size=(1000, 2))

In [53]:
xx, yy = _form_cvar_problem(y, 0, 2, self_regress=True)

In [51]:
xx.shape

(998, 4)

In [54]:
yy.shape

(998, 2)

In [55]:
y[0:10]

array([[ 3.42117331,  1.1027816 ],
       [ 0.38597627, -0.26155704],
       [ 0.49956691, -3.47782272],
       [-0.93883822,  0.55187893],
       [ 0.62690434, -0.09718924],
       [ 0.79133604, -0.32118519],
       [ 2.26426573,  0.77988712],
       [-0.47326591,  1.76506487],
       [-0.87732541,  0.78646346],
       [ 1.95102387, -1.31510677]])

In [56]:
xx[0:10]

array([[ 3.42117331,  1.1027816 , -3.03519704, -1.36433864],
       [ 0.38597627, -0.26155704,  0.11359064, -3.21626569],
       [ 0.49956691, -3.47782272, -1.43840513,  4.02970165],
       [-0.93883822,  0.55187893,  1.56574255, -0.64906817],
       [ 0.62690434, -0.09718924,  0.16443171, -0.22399595],
       [ 0.79133604, -0.32118519,  1.47292969,  1.10107231],
       [ 2.26426573,  0.77988712, -2.73753164,  0.98517776],
       [-0.47326591,  1.76506487, -0.40405949, -0.97860141],
       [-0.87732541,  0.78646346,  2.82834928, -2.10157023],
       [ 1.95102387, -1.31510677, -0.8504801 ,  0.13510653]])

In [57]:
yy[0:10]

array([[ 0.11359064,  3.14878768],
       [-1.43840513, -1.55199577],
       [ 1.56574255,  3.00414768],
       [ 0.16443171, -1.40131085],
       [ 1.47292969,  1.30849798],
       [-2.73753164, -4.21046133],
       [-0.40405949,  2.33347215],
       [ 2.82834928,  3.23240877],
       [-0.8504801 , -3.67882937],
       [-1.91069787, -1.06021777]])

In [58]:
y[2] + y[0] - 2 * y[1]

array([ 3.14878768, -1.85192704])

In [7]:
data_files = glob('/mnt/Secondary/data/sabes/indy*.mat')

In [8]:
dat = load_sabes(data_files[0])

Processing spikes


100%|██████████| 1/1 [00:04<00:00,  4.02s/it]


In [9]:
X = np.squeeze(dat['spike_rates'])

In [10]:
varmodelc = VAR(order=2, continuous=True)
varmodeld = VAR(order=2, continuous=False)

In [13]:
varmodelc.fit(X)

Rows of VAR matrix processed: 0it [00:00, ?it/s]

> /home/akumar/nse/PyUoI/pyuoi/linear_model/var.py(262)fit()
    260                     pdb.set_trace()
    261 
--> 262                     if distributed_save:
    263                         self.estimator.fit(xx, yy, savepath=savepaths[idx])
    264                     else:



Rows of VAR matrix processed: 0it [00:02, ?it/s]


ValueError: y should either have shape (n_samples, ) or (n_samples, 1).