In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
import numpy as np
import scipy 
from scipy.stats import ortho_group
import sys
import pdb
import matplotlib.pyplot as plt

In [4]:
sys.path.append('/home/akumar/nse/neural_control')

In [5]:
from orth_pca import OrthPCA

In [6]:
# Toy problem: Generate data from 2 correlated multivariate Gaussians
s = np.random.uniform(1, 10, size=(20,))
U = ortho_group.rvs(20)
S = U @ np.diag(s) @ U.T

S1 = S[0:10, 0:10]
S2 = S[10:, 10:]
x1 = np.random.multivariate_normal(mean=np.zeros(10,), cov=S1, size=int(1e3))
x2 = np.random.multivariate_normal(mean=np.zeros(10,), cov=S2, size=int(1e3))

In [7]:
opca = OrthPCA(5, 4)

v1, v2, cost = opca.fit(x1, x2)

In [19]:
cost

array(-3.17085801)

In [20]:
# How do we assess correctness? In the case when the variables are uncorrelated and the variances are high in different directions

In [76]:
#s = np.random.uniform(1, 10, size=(20,))
s = np.ones(20)
s[0] = 10
s[1] = 10
s = np.sort(s)
U = ortho_group.rvs(20)
S1 = np.diag(s)
s = s[::-1]
S2 = np.diag(s) 

In [77]:
x1 = np.random.multivariate_normal(mean=np.zeros(S1.shape[0],), cov=S1, size=int(1e3))
x2 = np.random.multivariate_normal(mean=np.zeros(S2.shape[0],), cov=S2, size=int(1e3))

In [79]:
opca = OrthPCA(2, 2)
v1, v2, cost = opca.fit(x1, x2)

Optimizing...
Iteration    Cost                       Gradient norm     
---------    -----------------------    --------------    
   1         -1.6496805436090972e-01    2.20336499e-01    
   2         -4.4325626021600739e-01    3.64814630e-01    
   3         -7.6079557912222584e-01    2.92647166e-01    
   4         -8.7107735430652422e-01    2.25300739e-01    
   5         -8.9705470323337400e-01    3.51607472e-01    
   6         -9.8583826936686103e-01    2.47089527e-01    
   7         -1.0465262133269673e+00    8.16401122e-02    
   8         -1.0530167237145780e+00    1.28721934e-02    
   9         -1.0531612657116800e+00    3.73820598e-03    
  10         -1.0531726420806948e+00    1.38967429e-03    
  11         -1.0531738733182252e+00    7.89312314e-04    
  12         -1.0531744558922651e+00    4.49314114e-05    
  13         -1.0531744576883231e+00    9.48538676e-06    
  14         -1.0531744577622479e+00    3.24034027e-06    
  15         -1.0531744577642184e+00    2.

In [80]:
np.diag(S2)

array([10., 10.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [35]:
np.diag(S1)

array([1.99918489, 2.19331574, 2.42964117, 2.5119952 , 2.81859447,
       3.56702381, 3.70946505, 4.10015276, 4.54285099, 5.35318668,
       5.51892151, 6.23763697, 6.37491186, 6.69471379, 6.79359576,
       6.8055461 , 7.22299319, 7.88964515, 8.24074071, 8.42712075])

In [81]:
v1

array([[ 2.57078604e-03, -1.62754427e-03],
       [ 4.97697462e-03, -2.47406833e-03],
       [-1.33420149e-02,  1.27885468e-02],
       [ 1.62586984e-02, -1.23095605e-02],
       [ 5.75256555e-03,  2.26271358e-03],
       [-2.08973017e-02,  2.51929563e-02],
       [ 1.69024944e-02, -9.61956733e-03],
       [-1.61287271e-02,  3.75059489e-03],
       [-1.67551709e-02,  2.33317250e-03],
       [-3.47390189e-03,  2.16577589e-02],
       [ 5.75833315e-03,  1.06635828e-02],
       [-7.55089629e-03, -5.79637948e-03],
       [ 5.23392173e-03, -2.61734656e-03],
       [-8.03776104e-03, -8.41459891e-03],
       [ 1.52188531e-03,  9.67310967e-03],
       [ 3.42178512e-03,  5.57229511e-04],
       [ 3.63094517e-04,  4.47780416e-03],
       [ 1.01569251e-02,  1.19992821e-02],
       [ 9.34777882e-01, -3.51420488e-01],
       [ 3.52290590e-01,  9.35134220e-01]])

In [82]:
v2

array([[-6.34274253e-01, -7.71315895e-01],
       [-7.71412600e-01,  6.34389384e-01],
       [ 5.97393589e-03, -1.25731887e-02],
       [-1.68967086e-03, -1.14230690e-02],
       [-1.38411794e-02,  7.45958192e-03],
       [-8.65059464e-03, -2.01480553e-02],
       [-7.95186643e-03,  2.18891781e-03],
       [ 4.46141317e-03, -2.63262905e-02],
       [ 4.31520598e-03, -4.49975976e-03],
       [-1.75862117e-02, -3.17673517e-03],
       [-3.70808300e-04, -1.46905152e-02],
       [ 1.80647559e-03, -1.47715186e-02],
       [ 1.84764217e-02,  2.09046704e-02],
       [-3.10520942e-04, -1.13282417e-02],
       [-1.45536866e-02, -8.27950121e-03],
       [ 1.17342111e-02, -1.96749607e-03],
       [ 2.81380921e-02, -8.03135936e-03],
       [ 1.95039483e-02,  4.79419907e-04],
       [ 5.98984354e-03, -2.64040697e-03],
       [-6.11529593e-04,  2.54598319e-04]])

In [83]:
cost

array(-1.05317446)

In [58]:
v1.T @ v2

array([[ 7.02563008e-17,  4.41053444e-16],
       [-6.07153217e-17, -1.27502175e-16]])

In [53]:
np.trace(v1.T @ S1 @ v1)

15.707200855371017

In [87]:
np.sum(s[0:2])/np.sum(s) * 2

1.0526315789473684

In [67]:
u1 = np.zeros((20, 2))
u1[-1, 0] = 1
u1[-2, 1] = 1
u2 = np.zeros((20, 2))
u2[0, 0] = 1
u2[1, 1] = 1

In [84]:
scipy.linalg.subspace_angles(u1, v1)

array([0.05474403, 0.0334033 ])

In [85]:
scipy.linalg.subspace_angles(u2, v2)

array([0.05265982, 0.04972136])

array([10., 10.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.])